export interface Movie 
{
    "_id": string,
    "id": string,
    "__v": any,
    "description":any,
    "director":any,
    "genre":any,
    trailer:any,
    favorite:boolean,
    isWatched:boolean,
    "image":any,
    "imdbid":any,
    "rank":any,
    "rating":any,
    "thumbnail":any,
    "title":any,
    "writers":any,
    "year":any,
}